name: Run spell check with Typos
on:
    workflow_dispatch:
    push:
    pull_request:

jobs:
    run:
        name: Spell Check with Typos
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Actions Repository
              uses: actions/checkout@v4
              with:
                ref: ${{ github.event.pull_request.head.sha }}
                # add a step that lists all files in the repository
            - name: list files
              run: ls -R
            - name: Use custom config file
              uses: crate-ci/typos@master
              with:
                  config: ./typos.toml
                  write_changes: true
                  files: "./src/docs/**/*"
